#!/bin/bash

BUFFETT="Life is like a snowball. The important thing is finding wet snow and a really long hill."

    ISAY=$BUFFETT
    Change1=${ISAY[@]/snow/foot}
    Change2=${Change1[@]//snow/}
    Change3=${Change2[@]/finding/getting}
    POS=0
    LEN=59
    ISAY=${Change3:$POS:$LEN}

echo "Warren Buffett said:"
echo $BUFFETT
echo "and I say:"
echo "$ISAY"
